export interface PatientType {
  patient_id: number;
  health_number: number;
  patient_name: string;
  room_id: number;
  active_patient: boolean;
}

export const patients = [
  {
    patient_id: 1,
    health_number: 10001,
    patient_name: "John Doe",
    room_id: 101,
    active_patient: true,
  },
  {
    patient_id: 2,
    health_number: 10002,
    patient_name: "Jane Smith",
    room_id: 102,
    active_patient: true,
  },
  {
    patient_id: 3,
    health_number: 10003,
    patient_name: "Alice Brown",
    room_id: 103,
    active_patient: true,
  },
  {
    patient_id: 4,
    health_number: 10004,
    patient_name: "Bob White",
    room_id: 104,
    active_patient: true,
  },
  {
    patient_id: 5,
    health_number: 10005,
    patient_name: "Chris Black",
    room_id: 105,
    active_patient: true,
  },
  {
    patient_id: 6,
    health_number: 10006,
    patient_name: "Diane Green",
    room_id: 106,
    active_patient: true,
  },

  {
    patient_id: 7,
    health_number: 10007,
    patient_name: "Edward Gray",
    room_id: 201,
    active_patient: true,
  },
  {
    patient_id: 8,
    health_number: 10008,
    patient_name: "Fiona Blue",
    room_id: 202,
    active_patient: true,
  },
  {
    patient_id: 9,
    health_number: 10009,
    patient_name: "George Silver",
    room_id: 203,
    active_patient: true,
  },
  {
    patient_id: 10,
    health_number: 10010,
    patient_name: "Hannah Violet",
    room_id: 204,
    active_patient: true,
  },
  {
    patient_id: 11,
    health_number: 10011,
    patient_name: "Ian Gold",
    room_id: 205,
    active_patient: true,
  },
  {
    patient_id: 12,
    health_number: 10012,
    patient_name: "Jill Crimson",
    room_id: 206,
    active_patient: true,
  },

  {
    patient_id: 13,
    health_number: 10013,
    patient_name: "Karen Indigo",
    room_id: 301,
    active_patient: true,
  },
  {
    patient_id: 14,
    health_number: 10014,
    patient_name: "Leo Magenta",
    room_id: 302,
    active_patient: true,
  },
  {
    patient_id: 15,
    health_number: 10015,
    patient_name: "Mia Amber",
    room_id: 303,
    active_patient: true,
  },
  {
    patient_id: 16,
    health_number: 10016,
    patient_name: "Nathan Teal",
    room_id: 304,
    active_patient: true,
  },
  {
    patient_id: 17,
    health_number: 10017,
    patient_name: "Olivia Lavender",
    room_id: 305,
    active_patient: true,
  },
  {
    patient_id: 18,
    health_number: 10018,
    patient_name: "Paul Ruby",
    room_id: 306,
    active_patient: true,
  },

  {
    patient_id: 19,
    health_number: 10019,
    patient_name: "Quincy Olive",
    room_id: 401,
    active_patient: true,
  },
  {
    patient_id: 20,
    health_number: 10020,
    patient_name: "Rachel Cyan",
    room_id: 402,
    active_patient: true,
  },
  {
    patient_id: 21,
    health_number: 10021,
    patient_name: "Samuel Plum",
    room_id: 403,
    active_patient: true,
  },
  {
    patient_id: 22,
    health_number: 10022,
    patient_name: "Tina Maroon",
    room_id: 404,
    active_patient: true,
  },
  {
    patient_id: 23,
    health_number: 10023,
    patient_name: "Uma Peach",
    room_id: 405,
    active_patient: true,
  },
  {
    patient_id: 24,
    health_number: 10024,
    patient_name: "Victor Mint",
    room_id: 406,
    active_patient: true,
  },

  {
    patient_id: 25,
    health_number: 10025,
    patient_name: "Willow Navy",
    room_id: 501,
    active_patient: true,
  },
  {
    patient_id: 26,
    health_number: 10026,
    patient_name: "Xander Steel",
    room_id: 502,
    active_patient: true,
  },
  {
    patient_id: 27,
    health_number: 10027,
    patient_name: "Yara Sky",
    room_id: 503,
    active_patient: true,
  },
  {
    patient_id: 28,
    health_number: 10028,
    patient_name: "Zane Rose",
    room_id: 504,
    active_patient: true,
  },
  {
    patient_id: 29,
    health_number: 10029,
    patient_name: "Amber Jade",
    room_id: 505,
    active_patient: true,
  },
  {
    patient_id: 30,
    health_number: 10030,
    patient_name: "Brian Emerald",
    room_id: 506,
    active_patient: true,
  },

  {
    patient_id: 31,
    health_number: 10031,
    patient_name: "Clara Pearl",
    room_id: 601,
    active_patient: true,
  },
  {
    patient_id: 32,
    health_number: 10032,
    patient_name: "Dylan Onyx",
    room_id: 602,
    active_patient: true,
  },
  {
    patient_id: 33,
    health_number: 10033,
    patient_name: "Ella Coral",
    room_id: 603,
    active_patient: true,
  },
  {
    patient_id: 34,
    health_number: 10034,
    patient_name: "Felix Ash",
    room_id: 604,
    active_patient: true,
  },
  {
    patient_id: 35,
    health_number: 10035,
    patient_name: "Grace Ivory",
    room_id: 605,
    active_patient: true,
  },
  {
    patient_id: 36,
    health_number: 10036,
    patient_name: "Henry Sage",
    room_id: 606,
    active_patient: true,
  },
];
